/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Samsung
 */
public class Mcp_JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Mcp_JFrmPrincipal
     */
    public Mcp_JFrmPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jBtnConsultarUsuarios = new javax.swing.JButton();
        jBtnConsultarClientes = new javax.swing.JButton();
        jBtnConsultarProdutos = new javax.swing.JButton();
        jBtnConsultarVendas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuCadastros = new javax.swing.JMenu();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuVendas = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMnuConsultasUsuarios = new javax.swing.JMenuItem();
        jMnuConsultasClientes = new javax.swing.JMenuItem();
        jMnuConsultasProdutos = new javax.swing.JMenuItem();
        jMnuConsultasVendas = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jBtnConsultarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-consulta-30.png"))); // NOI18N
        jBtnConsultarUsuarios.setFocusable(false);
        jBtnConsultarUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultarUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsultarUsuarios);

        jBtnConsultarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-atrair-clientes-30.png"))); // NOI18N
        jBtnConsultarClientes.setFocusable(false);
        jBtnConsultarClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultarClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsultarClientes);

        jBtnConsultarProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-caixa-30.png"))); // NOI18N
        jBtnConsultarProdutos.setFocusable(false);
        jBtnConsultarProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultarProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsultarProdutos);

        jBtnConsultarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-vendas-totais-30.png"))); // NOI18N
        jBtnConsultarVendas.setFocusable(false);
        jBtnConsultarVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultarVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsultarVendas);

        jMnuCadastros.setMnemonic('c');
        jMnuCadastros.setText("Cadastros");

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-grupo-de-usuário-mulher-mulher-24.png"))); // NOI18N
        jMnuUsuarios.setMnemonic('u');
        jMnuUsuarios.setText("Usuarios");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuUsuarios);

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-clientes-30.png"))); // NOI18N
        jMnuClientes.setMnemonic('c');
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuClientes);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-produto-24.png"))); // NOI18N
        jMnuProdutos.setMnemonic('p');
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuProdutos);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-dois-ingressos-24.png"))); // NOI18N
        jMenuItem1.setMnemonic('C');
        jMenuItem1.setText("Cupons");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMenuItem1);
        jMnuCadastros.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sair-24.png"))); // NOI18N
        jMnuSair.setMnemonic('s');
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuSair);

        jMenuBar1.add(jMnuCadastros);

        jMnuVendas.setMnemonic('V');
        jMnuVendas.setText("Movimento");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-vendas-24.png"))); // NOI18N
        jMenuItem2.setText("Vendas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMnuVendas.add(jMenuItem2);

        jMenuBar1.add(jMnuVendas);

        jMenu1.setText("Consultas");

        jMnuConsultasUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultasUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-consulta-30.png"))); // NOI18N
        jMnuConsultasUsuarios.setMnemonic('p');
        jMnuConsultasUsuarios.setText("Usuários");
        jMnuConsultasUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultasUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuConsultasUsuarios);

        jMnuConsultasClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultasClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-atrair-clientes-30.png"))); // NOI18N
        jMnuConsultasClientes.setMnemonic('p');
        jMnuConsultasClientes.setText("Clientes");
        jMnuConsultasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultasClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuConsultasClientes);

        jMnuConsultasProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultasProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-caixa-30.png"))); // NOI18N
        jMnuConsultasProdutos.setMnemonic('p');
        jMnuConsultasProdutos.setText("Produtos");
        jMnuConsultasProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultasProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuConsultasProdutos);

        jMnuConsultasVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultasVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-vendas-totais-30.png"))); // NOI18N
        jMnuConsultasVendas.setMnemonic('p');
        jMnuConsultasVendas.setText("Vendas");
        jMnuConsultasVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultasVendasActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuConsultasVendas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
        Mcp_JDlgUsuarios jDlgUsuarios = new Mcp_JDlgUsuarios(this, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
        // TODO add your handling code here:
        new view.Mcp_JDlgClientes(this, true).setVisible(true);
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        new view.Mcp_JDlgProduto(this, true).setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new view.Mcp_JDlgCupons(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new view.Mcp_JDlgVendas(this, true).setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMnuConsultasUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultasUsuariosActionPerformed
        // TODO add your handling code here:
        new view.Mcp_JDlgConsultaUsuarios(this, true).setVisible(true);
    }//GEN-LAST:event_jMnuConsultasUsuariosActionPerformed

    private void jMnuConsultasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultasClientesActionPerformed
        // TODO add your handling code here:
        new view.Mcp_JDlgConsultaClientes(this, true).setVisible(true);
    }//GEN-LAST:event_jMnuConsultasClientesActionPerformed

    private void jMnuConsultasProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultasProdutosActionPerformed
        // TODO add your handling code here:
         new view.Mcp_JDlgConsultaProdutos(this, true).setVisible(true);
    }//GEN-LAST:event_jMnuConsultasProdutosActionPerformed

    private void jMnuConsultasVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultasVendasActionPerformed
        // TODO add your handling code here:
        new view.Mcp_JDlgConsultaVendas(this, true).setVisible(true);
    }//GEN-LAST:event_jMnuConsultasVendasActionPerformed

    private void jBtnConsultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarUsuariosActionPerformed
        // TODO add your handling code here:
         new view.Mcp_JDlgConsultaUsuarios(this, true).setVisible(true);
    }//GEN-LAST:event_jBtnConsultarUsuariosActionPerformed

    private void jBtnConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarClientesActionPerformed
        // TODO add your handling code here:
        new view.Mcp_JDlgConsultaClientes(this, true).setVisible(true);
    }//GEN-LAST:event_jBtnConsultarClientesActionPerformed

    private void jBtnConsultarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarProdutosActionPerformed
        // TODO add your handling code here:
        new view.Mcp_JDlgConsultaProdutos(this, true).setVisible(true);
    }//GEN-LAST:event_jBtnConsultarProdutosActionPerformed

    private void jBtnConsultarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarVendasActionPerformed
        // TODO add your handling code here:
        new view.Mcp_JDlgConsultaVendas(this, true).setVisible(true);
    }//GEN-LAST:event_jBtnConsultarVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mcp_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mcp_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mcp_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mcp_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mcp_JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultarClientes;
    private javax.swing.JButton jBtnConsultarProdutos;
    private javax.swing.JButton jBtnConsultarUsuarios;
    private javax.swing.JButton jBtnConsultarVendas;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMnuCadastros;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenuItem jMnuConsultasClientes;
    private javax.swing.JMenuItem jMnuConsultasProdutos;
    private javax.swing.JMenuItem jMnuConsultasUsuarios;
    private javax.swing.JMenuItem jMnuConsultasVendas;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenu jMnuVendas;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
