/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import bean.McpUsuarios;
import com.itextpdf.text.Element;
import com.itextpdf.text.Phrase;
import dao.Mcp_UsuariosDAO;
import dao.Mcp_UsuariosDAO;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import tools.PdfUtil;
import tools.mcp_util;
import view.Mcp_JDlgUsuarios;

/**
 *
 * @author Marcos
 */
public class Mcp_JDlgConsultaUsuarios extends javax.swing.JDialog {
   Mcp_ControllerConsultasUsuarios controllerConsultasUsuarios;
    /**
     * Creates new form JDlgUsuariosPesquisar
     */
 
    public Mcp_JDlgConsultaUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pesquisar Usuarios");
   
        controllerConsultasUsuarios = new Mcp_ControllerConsultasUsuarios();
        Mcp_UsuariosDAO produtosDAO = new Mcp_UsuariosDAO();
        List lista = new ArrayList();
        controllerConsultasUsuarios.setList(lista);
        jTable1.setModel(controllerConsultasUsuarios);
        
        Mcp_UsuariosDAO usuariosDAO = new Mcp_UsuariosDAO();
        List<McpUsuarios> listaUsuarios = (List<McpUsuarios>) usuariosDAO.listAll();

        jCboNivelUsu.removeAllItems();
        jCboNivelUsu.addItem("Todos");

        for (McpUsuarios c : listaUsuarios) {
            jCboNivelUsu.removeAllItems();
            jCboNivelUsu.addItem("Todos");       
            jCboNivelUsu.addItem("Administrador");
            jCboNivelUsu.addItem("Funcionário");
            jCboNivelUsu.addItem("Convidado");
        }
  
    //    controllerUsuarios = new ControllerUsuarios();
    //    UsuariosDAO usuariosDAO = new UsuariosDAO();
    //    List lista = (List) usuariosDAO.listAll();
    //    controllerUsuarios.setList(lista);
    //    jTable1.setModel(controllerUsuarios);
    
    }
    private void gerarPDF() {
    try {
        
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Salvar PDF");
        chooser.setSelectedFile(new File("usuarios.pdf")); 
        int result = chooser.showSaveDialog(this);

        if (result != JFileChooser.APPROVE_OPTION) {
            return; 
        }
        String caminho = chooser.getSelectedFile().getAbsolutePath();
        if (!caminho.toLowerCase().endsWith(".pdf")) {
            caminho += ".pdf";
        }
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(caminho));
        document.open();

        document.add(new Paragraph("RELATÓRIO DE USUÁRIOS"));
        document.add(new Paragraph("\n"));
        Mcp_UsuariosDAO usuariosDAO = new Mcp_UsuariosDAO();
        List<McpUsuarios> lista = (List<McpUsuarios>) usuariosDAO.listAll();

        PdfPTable tabela = new PdfPTable(4);
        tabela.addCell("Código");
        tabela.addCell("Nome");
        tabela.addCell("Apelido");
        tabela.addCell("CPF");

        for (McpUsuarios u : lista) {
            tabela.addCell(String.valueOf(u.getMcpIdUsuario()));
            tabela.addCell(u.getMcpNome());
            tabela.addCell(u.getMcpApelido());
            tabela.addCell(u.getMcpCpf());
        }

        document.add(tabela);
        document.close();

        JOptionPane.showMessageDialog(this, "PDF gerado com sucesso em:\n" + caminho);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao gerar PDF: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jBtnConsultar = new javax.swing.JButton();
        jBtnPDF1 = new javax.swing.JButton();
        jBtnOk1 = new javax.swing.JButton();
        jCboNivelUsu = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Nome");

        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });

        jBtnPDF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pdf-30.png"))); // NOI18N
        jBtnPDF1.setText("GERAR PDF");
        jBtnPDF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPDF1ActionPerformed(evt);
            }
        });

        jBtnOk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ok-24.png"))); // NOI18N
        jBtnOk1.setText("OK");
        jBtnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOk1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nivel dos usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnPDF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCboNivelUsu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addComponent(jBtnConsultar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnConsultar)
                            .addComponent(jCboNivelUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPDF1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        // TODO add your handling code here:
        Mcp_UsuariosDAO usuariosDAO = new Mcp_UsuariosDAO();
    List lista;

        if ((jTxtNome.getText().length() > 0)
                && (jCboNivelUsu.getSelectedIndex() != -1 && !jCboNivelUsu.getSelectedItem().toString().equals("Todos"))) {
            lista = (List) usuariosDAO.listNomeNivel(
                    jTxtNome.getText(),
                    jCboNivelUsu.getSelectedItem().toString()
            );
        } else if (jTxtNome.getText().length() > 0) {
            lista = (List) usuariosDAO.listNome(jTxtNome.getText());
        } else if (jCboNivelUsu.getSelectedIndex() != -1 && !jCboNivelUsu.getSelectedItem().toString().equals("Todos")) {
            lista = (List) usuariosDAO.listNivel(jCboNivelUsu.getSelectedItem().toString());
        } else {
            lista = (List) usuariosDAO.listAll();
        }

    controllerConsultasUsuarios.setList(lista);

    if (lista.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
            this, 
            "Nenhum usuário encontrado com os critérios informados.", 
            "Consulta", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }
    }//GEN-LAST:event_jBtnConsultarActionPerformed

    private void jBtnPDF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPDF1ActionPerformed
        // TODO add your handling code here:
        gerarPDF();
    }//GEN-LAST:event_jBtnPDF1ActionPerformed

    private void jBtnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOk1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnOk1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mcp_JDlgConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mcp_JDlgConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mcp_JDlgConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mcp_JDlgConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Mcp_JDlgConsultaUsuarios dialog = new Mcp_JDlgConsultaUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnOk1;
    private javax.swing.JButton jBtnPDF1;
    private javax.swing.JComboBox jCboNivelUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables
}
