package bean;
// Generated 13/10/2025 23:06:47 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * McpCupons generated by hbm2java
 */
@Entity
@Table(name="mcp_cupons"
    ,catalog="vendas"
    , uniqueConstraints = @UniqueConstraint(columnNames="mcp_nome") 
)
public class McpCupons  implements java.io.Serializable {


     private int mcpIdCupom;
     private String mcpNome;
     private String mcpDescricao;
     private String mcpTipoDesconto;
     private Date mcpDataValidade;
     private String mcpAtivo;
     private String mcpUtilizacoes;
     

    public McpCupons() {
    }

	
    public McpCupons(int mcpIdCupom, String mcpNome, String mcpTipoDesconto, Date mcpDataValidade, String mcpAtivo) {
        this.mcpIdCupom = mcpIdCupom;
        this.mcpNome = mcpNome;
        this.mcpTipoDesconto = mcpTipoDesconto;
        this.mcpDataValidade = mcpDataValidade;
        this.mcpAtivo = mcpAtivo;
    }
    public McpCupons(int mcpIdCupom, String mcpNome, String mcpDescricao, String mcpTipoDesconto, Date mcpDataValidade, String mcpAtivo, String mcpUtilizacoes, Set mcpVendases) {
       this.mcpIdCupom = mcpIdCupom;
       this.mcpNome = mcpNome;
       this.mcpDescricao = mcpDescricao;
       this.mcpTipoDesconto = mcpTipoDesconto;
       this.mcpDataValidade = mcpDataValidade;
       this.mcpAtivo = mcpAtivo;
       this.mcpUtilizacoes = mcpUtilizacoes;
       
    }
   
     @Id 

    
    @Column(name="mcp_idCupom", unique=true, nullable=false)
    public int getMcpIdCupom() {
        return this.mcpIdCupom;
    }
    
    public void setMcpIdCupom(int mcpIdCupom) {
        this.mcpIdCupom = mcpIdCupom;
    }

    
    @Column(name="mcp_nome", unique=true, nullable=false, length=20)
    public String getMcpNome() {
        return this.mcpNome;
    }
    
    public void setMcpNome(String mcpNome) {
        this.mcpNome = mcpNome;
    }

    
    @Column(name="mcp_descricao", length=65535)
    public String getMcpDescricao() {
        return this.mcpDescricao;
    }
    
    public void setMcpDescricao(String mcpDescricao) {
        this.mcpDescricao = mcpDescricao;
    }

    
    @Column(name="mcp_tipoDesconto", nullable=false, length=20)
    public String getMcpTipoDesconto() {
        return this.mcpTipoDesconto;
    }
    
    public void setMcpTipoDesconto(String mcpTipoDesconto) {
        this.mcpTipoDesconto = mcpTipoDesconto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mcp_dataValidade", length=10)
    public Date getMcpDataValidade() {
        return this.mcpDataValidade;
    }
    
    public void setMcpDataValidade(Date mcpDataValidade) {
        this.mcpDataValidade = mcpDataValidade;
    }

    
    @Column(name="mcp_ativo", nullable=false, length=1)
    public String getMcpAtivo() {
        return this.mcpAtivo;
    }
    
    public void setMcpAtivo(String mcpAtivo) {
        this.mcpAtivo = mcpAtivo;
    }

    
    @Column(name="mcp_utilizacoes", length=11)
    public String getMcpUtilizacoes() {
        return this.mcpUtilizacoes;
    }
    
    public void setMcpUtilizacoes(String mcpUtilizacoes) {
        this.mcpUtilizacoes = mcpUtilizacoes;
    }

}


