package bean;
// Generated 13/10/2025 23:06:47 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * McpClientes generated by hbm2java
 */
@Entity
@Table(name="mcp_clientes"
    ,catalog="vendas"
    , uniqueConstraints = @UniqueConstraint(columnNames="mcp_cpf") 
)
public class McpClientes  implements java.io.Serializable {


     private int mcpIdClientes;
     private String mcpNome;
     private String mcpCpf;
     private String mcpTelefone;
     private String mcpEmail;
     private String mcpEndereco;
     private Date mcpDataCadastro;
     private String mcpAtivo;
     private String mcpCidade;
     private String mcpEstado;
     private String mcpCep;
     private String mcpSexo;
     private Date mcpDataNascimento;
     private double mcpRendaMensal;
     private String mcpObservacoes;
     private Set mcpVendases = new HashSet(0);

    public McpClientes() {
    }

	
    public McpClientes(String mcpNome, String mcpCpf, Date mcpDataCadastro, Date mcpDataNascimento) {
        this.mcpNome = mcpNome;
        this.mcpCpf = mcpCpf;
        this.mcpDataCadastro = mcpDataCadastro;
        this.mcpDataNascimento = mcpDataNascimento;
    }
    public McpClientes(String mcpNome, String mcpCpf, String mcpTelefone, String mcpEmail, String mcpEndereco, Date mcpDataCadastro, String mcpAtivo, String mcpCidade, String mcpEstado, String mcpCep, String mcpSexo, Date mcpDataNascimento, double mcpRendaMensal, String mcpObservacoes, Set mcpVendases) {
       this.mcpNome = mcpNome;
       this.mcpCpf = mcpCpf;
       this.mcpTelefone = mcpTelefone;
       this.mcpEmail = mcpEmail;
       this.mcpEndereco = mcpEndereco;
       this.mcpDataCadastro = mcpDataCadastro;
       this.mcpAtivo = mcpAtivo;
       this.mcpCidade = mcpCidade;
       this.mcpEstado = mcpEstado;
       this.mcpCep = mcpCep;
       this.mcpSexo = mcpSexo;
       this.mcpDataNascimento = mcpDataNascimento;
       this.mcpRendaMensal = mcpRendaMensal;
       this.mcpObservacoes = mcpObservacoes;
       this.mcpVendases = mcpVendases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mcp_idClientes", unique=true, nullable=false)
    public int getMcpIdClientes() {
        return this.mcpIdClientes;
    }
    
    public void setMcpIdClientes(int mcpIdClientes) {
        this.mcpIdClientes = mcpIdClientes;
    }

    
    @Column(name="mcp_nome", nullable=false, length=100)
    public String getMcpNome() {
        return this.mcpNome;
    }
    
    public void setMcpNome(String mcpNome) {
        this.mcpNome = mcpNome;
    }

    
    @Column(name="mcp_cpf", unique=true, nullable=false, length=14)
    public String getMcpCpf() {
        return this.mcpCpf;
    }
    
    public void setMcpCpf(String mcpCpf) {
        this.mcpCpf = mcpCpf;
    }

    
    @Column(name="mcp_telefone", length=15)
    public String getMcpTelefone() {
        return this.mcpTelefone;
    }
    
    public void setMcpTelefone(String mcpTelefone) {
        this.mcpTelefone = mcpTelefone;
    }

    
    @Column(name="mcp_email", length=80)
    public String getMcpEmail() {
        return this.mcpEmail;
    }
    
    public void setMcpEmail(String mcpEmail) {
        this.mcpEmail = mcpEmail;
    }

    
    @Column(name="mcp_endereco", length=150)
    public String getMcpEndereco() {
        return this.mcpEndereco;
    }
    
    public void setMcpEndereco(String mcpEndereco) {
        this.mcpEndereco = mcpEndereco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mcp_dataCadastro", nullable=false, length=10)
    public Date getMcpDataCadastro() {
        return this.mcpDataCadastro;
    }
    
    public void setMcpDataCadastro(Date mcpDataCadastro) {
        this.mcpDataCadastro = mcpDataCadastro;
    }

    
    @Column(name="mcp_ativo", length=1)
    public String getMcpAtivo() {
        return this.mcpAtivo;
    }
    
    public void setMcpAtivo(String mcpAtivo) {
        this.mcpAtivo = mcpAtivo;
    }

    
    @Column(name="mcp_cidade", length=50)
    public String getMcpCidade() {
        return this.mcpCidade;
    }
    
    public void setMcpCidade(String mcpCidade) {
        this.mcpCidade = mcpCidade;
    }

    
    @Column(name="mcp_estado", length=2)
    public String getMcpEstado() {
        return this.mcpEstado;
    }
    
    public void setMcpEstado(String mcpEstado) {
        this.mcpEstado = mcpEstado;
    }

    
    @Column(name="mcp_cep", length=9)
    public String getMcpCep() {
        return this.mcpCep;
    }
    
    public void setMcpCep(String mcpCep) {
        this.mcpCep = mcpCep;
    }

    
    @Column(name="mcp_sexo", length=1)
    public String getMcpSexo() {
        return this.mcpSexo;
    }
    
    public void setMcpSexo(String mcpSexo) {
        this.mcpSexo = mcpSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mcp_dataNascimento", nullable=false, length=10)
    public Date getMcpDataNascimento() {
        return this.mcpDataNascimento;
    }
    
    public void setMcpDataNascimento(Date mcpDataNascimento) {
        this.mcpDataNascimento = mcpDataNascimento;
    }

    
    @Column(name="mcp_rendaMensal", precision=10)
    public double getMcpRendaMensal() {
        return this.mcpRendaMensal;
    }
    
    public void setMcpRendaMensal(double mcpRendaMensal) {
        this.mcpRendaMensal = mcpRendaMensal;
    }

    
    @Column(name="mcp_observacoes", length=65535)
    public String getMcpObservacoes() {
        return this.mcpObservacoes;
    }
    
    public void setMcpObservacoes(String mcpObservacoes) {
        this.mcpObservacoes = mcpObservacoes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mcpClientes")
    public Set getMcpVendases() {
        return this.mcpVendases;
    }
    
    public void setMcpVendases(Set mcpVendases) {
        this.mcpVendases = mcpVendases;
    }




}


