package bean;
// Generated 13/10/2025 23:06:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import tools.mcp_util;

/**
 * McpProdutos generated by hbm2java
 */
@Entity
@Table(name="mcp_produtos"
    ,catalog="vendas"
)
public class McpProdutos  implements java.io.Serializable {


     private int mcpIdProdutos;
     private String mcpNome;
     private String mcpMarca;
     private String mcpTamanho;
     private double mcpPreco;
     private String mcpCategoria;
     private String mcpDescricao;
     private String mcpLancamento;
     

    public McpProdutos() {
    }

	
    public McpProdutos(String mcpNome, String mcpMarca, String mcpTamanho, double mcpPreco) {
        this.mcpNome = mcpNome;
        this.mcpMarca = mcpMarca;
        this.mcpTamanho = mcpTamanho;
        this.mcpPreco = mcpPreco;
    }
    public McpProdutos(String mcpNome, String mcpMarca, String mcpTamanho, String mcpPreco, String mcpCategoria, String mcpDescricao, String mcpLancamento, Set mcpVendasProdutoses) {
       this.mcpNome = mcpNome;
       this.mcpMarca = mcpMarca;
       this.mcpTamanho = mcpTamanho;
       this.mcpPreco =mcp_util.strToDouble(mcpPreco);
       this.mcpCategoria = mcpCategoria;
       this.mcpDescricao = mcpDescricao;
       this.mcpLancamento = mcpLancamento;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mcp_idProdutos", unique=true, nullable=false)
    public int getMcpIdProdutos() {
        return this.mcpIdProdutos;
    }
    
    public void setMcpIdProdutos(int mcpIdProdutos) {
        this.mcpIdProdutos = mcpIdProdutos;
    }

    
    @Column(name="mcp_nome", nullable=false, length=100)
    public String getMcpNome() {
        return this.mcpNome;
    }
    
    public void setMcpNome(String mcpNome) {
        this.mcpNome = mcpNome;
    }

    
    @Column(name="mcp_marca", nullable=false, length=50)
    public String getMcpMarca() {
        return this.mcpMarca;
    }
    
    public void setMcpMarca(String mcpMarca) {
        this.mcpMarca = mcpMarca;
    }

    
    @Column(name="mcp_tamanho", nullable=false, length=5)
    public String getMcpTamanho() {
        return this.mcpTamanho;
    }
    
    public void setMcpTamanho(String mcpTamanho) {
        this.mcpTamanho = mcpTamanho;
    }

    
    @Column(name="mcp_preco", nullable=false, length=10)
    public double getMcpPreco() {
        return this.mcpPreco;
    }
    
    public void setMcpPreco(double mcpPreco) {
        this.mcpPreco = mcpPreco;
    }

    
    @Column(name="mcp_categoria", length=50)
    public String getMcpCategoria() {
        return this.mcpCategoria;
    }
    
    public void setMcpCategoria(String mcpCategoria) {
        this.mcpCategoria = mcpCategoria;
    }

    
    @Column(name="mcp_descricao", length=65535)
    public String getMcpDescricao() {
        return this.mcpDescricao;
    }
    
    public void setMcpDescricao(String mcpDescricao) {
        this.mcpDescricao = mcpDescricao;
    }

    
    @Column(name="mcp_lancamento", length=20)
    public String getMcpLancamento() {
        return this.mcpLancamento;
    }
    
    public void setMcpLancamento(String mcpLancamento) {
        this.mcpLancamento = mcpLancamento;
    }
    public String toString() {
        return this.mcpIdProdutos + " - " + this.mcpNome;
    }

}


