package bean;
// Generated 13/10/2025 23:06:47 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * McpUsuarios generated by hbm2java
 */
@Entity
@Table(name="mcp_usuarios"
    ,catalog="db_matheus_perdomo"
    , uniqueConstraints = @UniqueConstraint(columnNames="mcp_cpf") 
)
public class McpUsuarios  implements java.io.Serializable {


     private int mcpIdUsuario;
     private String mcpNome;
     private String mcpApelido;
     private String mcpCpf;
     private Date mcpDataNascimento;
     private String mcpSenha;
     private String mcpNivel;
     private String mcpAtivo;

    public McpUsuarios() {
    }

	
    public McpUsuarios(String mcpNome, String mcpApelido, String mcpCpf, Date mcpDataNascimento, String mcpSenha, String mcpNivel) {
        this.mcpNome = mcpNome;
        this.mcpApelido = mcpApelido;
        this.mcpCpf = mcpCpf;
        this.mcpDataNascimento = mcpDataNascimento;
        this.mcpSenha = mcpSenha;
        this.mcpNivel = mcpNivel;
    }
    public McpUsuarios(String mcpNome, String mcpApelido, String mcpCpf, Date mcpDataNascimento, String mcpSenha, String mcpNivel, String mcpAtivo) {
       this.mcpNome = mcpNome;
       this.mcpApelido = mcpApelido;
       this.mcpCpf = mcpCpf;
       this.mcpDataNascimento = mcpDataNascimento;
       this.mcpSenha = mcpSenha;
       this.mcpNivel = mcpNivel;
       this.mcpAtivo = mcpAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mcp_idUsuario", unique=true, nullable=false)
    public int getMcpIdUsuario() {
        return this.mcpIdUsuario;
    }
    
    public void setMcpIdUsuario(int mcpIdUsuario) {
        this.mcpIdUsuario = mcpIdUsuario;
    }

    
    @Column(name="mcp_nome", nullable=false, length=100)
    public String getMcpNome() {
        return this.mcpNome;
    }
    
    public void setMcpNome(String mcpNome) {
        this.mcpNome = mcpNome;
    }

    
    @Column(name="mcp_apelido", nullable=false, length=50)
    public String getMcpApelido() {
        return this.mcpApelido;
    }
    
    public void setMcpApelido(String mcpApelido) {
        this.mcpApelido = mcpApelido;
    }

    
    @Column(name="mcp_cpf", unique=true, nullable=false, length=14)
    public String getMcpCpf() {
        return this.mcpCpf;
    }
    
    public void setMcpCpf(String mcpCpf) {
        this.mcpCpf = mcpCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mcp_dataNascimento", length=10)
    public Date getMcpDataNascimento() {
        return this.mcpDataNascimento;
    }
    
    public void setMcpDataNascimento(Date mcpDataNascimento) {
        this.mcpDataNascimento = mcpDataNascimento;
    }

    
    @Column(name="mcp_senha", nullable=false)
    public String getMcpSenha() {
        return this.mcpSenha;
    }
    
    public void setMcpSenha(String mcpSenha) {
        this.mcpSenha = mcpSenha;
    }

    
    @Column(name="mcp_nivel", nullable=false, length=20)
    public String getMcpNivel() {
        return this.mcpNivel;
    }
    
    public void setMcpNivel(String mcpNivel) {
        this.mcpNivel = mcpNivel;
    }

    
    @Column(name="mcp_ativo", length=1)
    public String getMcpAtivo() {
        return this.mcpAtivo;
    }
    
    public void setMcpAtivo(String mcpAtivo) {
        this.mcpAtivo = mcpAtivo;
    }




}


