package bean;
// Generated 13/10/2025 23:06:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * McpVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="mcp_vendas_produtos"
    ,catalog="db_matheus_perdomo"
)
public class McpVendasProdutos  implements java.io.Serializable {


     private int mcpIdVendaProduto;
     private McpProdutos mcpProdutos;
     private McpVendas mcpVendas;
     private int mcpQuantidade;
     private int mcpValorUnitario;
     private int mcpDesconto;
     private int mcpSubtotal;

    public McpVendasProdutos() {
    }

	
    public McpVendasProdutos(int mcpQuantidade, int mcpValorUnitario, int mcpSubtotal) {
        this.mcpQuantidade = mcpQuantidade;
        this.mcpValorUnitario = mcpValorUnitario;
        this.mcpSubtotal = mcpSubtotal;
    }
    public McpVendasProdutos(McpProdutos mcpProdutos, McpVendas mcpVendas, int mcpQuantidade, int mcpValorUnitario, int mcpDesconto, int mcpSubtotal) {
       this.mcpProdutos = mcpProdutos;
       this.mcpVendas = mcpVendas;
       this.mcpQuantidade = mcpQuantidade;
       this.mcpValorUnitario = mcpValorUnitario;
       this.mcpDesconto = mcpDesconto;
       this.mcpSubtotal = mcpSubtotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mcp_idVendaProduto", unique=true, nullable=false)
    public int getMcpIdVendaProduto() {
        return this.mcpIdVendaProduto;
    }
    
    public void setMcpIdVendaProduto(int mcpIdVendaProduto) {
        this.mcpIdVendaProduto = mcpIdVendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mcp_idProduto")
    public McpProdutos getMcpProdutos() {
        return this.mcpProdutos;
    }
    
    public void setMcpProdutos(McpProdutos mcpProdutos) {
        this.mcpProdutos = mcpProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mcp_idVenda")
    public McpVendas getMcpVendas() {
        return this.mcpVendas;
    }
    
    public void setMcpVendas(McpVendas mcpVendas) {
        this.mcpVendas = mcpVendas;
    }

    
    @Column(name="mcp_quantidade", nullable=false)
    public int getMcpQuantidade() {
        return this.mcpQuantidade;
    }
    
    public void setMcpQuantidade(int mcpQuantidade) {
        this.mcpQuantidade = mcpQuantidade;
    }

    
    @Column(name="mcp_valorUnitario", nullable=false)
    public int getMcpValorUnitario() {
        return this.mcpValorUnitario;
    }
    
    public void setMcpValorUnitario(int mcpValorUnitario) {
        this.mcpValorUnitario = mcpValorUnitario;
    }

    
    @Column(name="mcp_desconto")
    public int getMcpDesconto() {
        return this.mcpDesconto;
    }
    
    public void setMcpDesconto(int mcpDesconto) {
        this.mcpDesconto = mcpDesconto;
    }

    
    @Column(name="mcp_subtotal", nullable=false)
    public int getMcpSubtotal() {
        return this.mcpSubtotal;
    }
    
    public void setMcpSubtotal(int mcpSubtotal) {
        this.mcpSubtotal = mcpSubtotal;
    }




}


