package bean;
// Generated 13/10/2025 23:06:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * McpVendas generated by hbm2java
 */
@Entity
@Table(name="mcp_vendas"
    ,catalog="vendas"
)
public class McpVendas  implements java.io.Serializable {


     private int mcpIdVenda;
     private McpClientes mcpClientes;
     private McpCupons mcpCupons;
     private String mcpDataVenda;
     private String mcpTotal;
     private String mcpFormaPagamento;
     private String mcpStatus;
     private String mcpObservacoes;
     

    public McpVendas() {
    }

	
    public McpVendas(McpClientes mcpClientes, String mcpTotal, String mcpFormaPagamento) {
        this.mcpClientes = mcpClientes;
        this.mcpTotal = mcpTotal;
        this.mcpFormaPagamento = mcpFormaPagamento;
    }
    public McpVendas(McpClientes mcpClientes, McpCupons mcpCupons, String mcpDataVenda, String mcpTotal, String mcpFormaPagamento, String mcpStatus, String mcpObservacoes, Set mcpVendasProdutoses) {
       this.mcpClientes = mcpClientes;
       this.mcpCupons = mcpCupons;
       this.mcpDataVenda = mcpDataVenda;
       this.mcpTotal = mcpTotal;
       this.mcpFormaPagamento = mcpFormaPagamento;
       this.mcpStatus = mcpStatus;
       this.mcpObservacoes = mcpObservacoes;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mcp_idVenda", unique=true, nullable=false)
    public int getMcpIdVenda() {
        return this.mcpIdVenda;
    }
    
    public void setMcpIdVenda(int mcpIdVenda) {
        this.mcpIdVenda = mcpIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mcp_idCliente", nullable=false)
    public McpClientes getMcpClientes() {
        return this.mcpClientes;
    }
    
    public void setMcpClientes(McpClientes mcpClientes) {
        this.mcpClientes = mcpClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mcp_idCupom")
    public McpCupons getMcpCupons() {
        return this.mcpCupons;
    }
    
    public void setMcpCupons(McpCupons mcpCupons) {
        this.mcpCupons = mcpCupons;
    }

    
    @Column(name="mcp_dataVenda", length=100)
    public String getMcpDataVenda() {
        return this.mcpDataVenda;
    }
    
    public void setMcpDataVenda(String mcpDataVenda) {
        this.mcpDataVenda = mcpDataVenda;
    }

    
    @Column(name="mcp_total", nullable=false, length=50)
    public String getMcpTotal() {
        return this.mcpTotal;
    }
    
    public void setMcpTotal(String mcpTotal) {
        this.mcpTotal = mcpTotal;
    }

    
    @Column(name="mcp_formaPagamento", nullable=false, length=20)
    public String getMcpFormaPagamento() {
        return this.mcpFormaPagamento;
    }
    
    public void setMcpFormaPagamento(String mcpFormaPagamento) {
        this.mcpFormaPagamento = mcpFormaPagamento;
    }

    
    @Column(name="mcp_status", length=20)
    public String getMcpStatus() {
        return this.mcpStatus;
    }
    
    public void setMcpStatus(String mcpStatus) {
        this.mcpStatus = mcpStatus;
    }

    
    @Column(name="mcp_observacoes", length=100)
    public String getMcpObservacoes() {
        return this.mcpObservacoes;
    }
    
    public void setMcpObservacoes(String mcpObservacoes) {
        this.mcpObservacoes = mcpObservacoes;
    }

}


